version: '3.7'
services:
  # Elasticsearch
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - bootstrap.memory_lock=true
      - cluster.initial_master_nodes=es
      - cluster.name=tfedb
      - node.name=es
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - /usr/share/elasticsearch/data
    # Exposed for development.
    ports:
      - 9200:9200

  # Provisioning
  provision:
    image: tfedb-data:latest
    depends_on:
      - es
    deploy:
      restart_policy:
        condition: none
    environment:
      ES_URL: 'http://es:9200'

  # API
  api:
    image: tfedb-api:latest
    depends_on:
      - es
    environment:
      CORS_DOMAINS: "*.tfedb.com,localhost"
      ES_URL: 'http://es:9200'
    networks:
      - default
      - external
    # Exposed for development.
    ports:
      - 8080:8080

networks:
  external:
    external:
      name: external